[build]
  base = "/"
  command = "npm run build"
  publish = ".output/public"

[build.environment]
  NODE_VERSION = "20"

# Nuxt 4 SSR deployment - no redirects needed as Nuxt handles routing server-side

# Environment variables should be set in Netlify UI:
# - VITE_AIRTABLE_TOKEN
# - VITE_AIRTABLE_BASE_ID
# - VITE_AIRTABLE_TABLE_NAME
# - VITE_AIRTABLE_VIEW_ID
# - VITE_AIRTABLE_LOCATIONS_TABLE_NAME
