class AirtableService {
  async fetchData() {
    try {
      // Always use cache files (pre-generated by prebuild script)
      const cache = await import('../data/airtable-cache.json')
      return cache.default?.data || cache.data
    } catch (error) {
      console.error('Error loading airtable cache:', error)
      throw new Error('Failed to load beverage data from cache. Run "npm run prebuild" to fetch fresh data.')
    }
  }

  async getData() {
    return this.fetchData()
  }
}

export default new AirtableService()