// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 10/3/2025, 7:37:48 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/Users/marcbroad/Desktop/www/__vite/piesanos-lbw/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/marcbroad/Desktop/www/__vite/piesanos-lbw/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/marcbroad/Desktop/www/__vite/piesanos-lbw/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/marcbroad/Desktop/www/__vite/piesanos-lbw/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/marcbroad/Desktop/www/__vite/piesanos-lbw/plugins/**/*.{js,ts,mjs}","/Users/marcbroad/Desktop/www/__vite/piesanos-lbw/composables/**/*.{js,ts,mjs}","/Users/marcbroad/Desktop/www/__vite/piesanos-lbw/utils/**/*.{js,ts,mjs}","/Users/marcbroad/Desktop/www/__vite/piesanos-lbw/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/marcbroad/Desktop/www/__vite/piesanos-lbw/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/marcbroad/Desktop/www/__vite/piesanos-lbw/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/marcbroad/Desktop/www/__vite/piesanos-lbw/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;