name: Daily Netlify Rebuild

on:
  schedule:
    # Run daily at 6:00 AM UTC (adjust timezone as needed)
    - cron: '0 6 * * *'
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  trigger-netlify-build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Netlify Build
        run: |
          echo "Triggering Netlify build to fetch fresh Airtable data..."
          curl -X POST -d {} ${{ secrets.NETLIFY_BUILD_HOOK_URL }}
          echo "✅ Build triggered successfully!"
